"use client";

import {useEffect,useMemo,useState} from "react";
import Image from "next/image";
import Link from "next/link";
import {format} from "date-fns";
import {ptBR} from "date-fns/locale";
import {ArrowLeft,Ban,CalendarDays,CalendarPlus,CalendarRange,Check,CheckCircle2,ChevronLeft,ChevronRight,CircleDollarSign,Clock3,LayoutDashboard,MessageCircle,MoreHorizontal,Pencil,Plus,Scissors,Search,Trash2,UserRound,UsersRound,XCircle} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from "@/components/ui/dropdown-menu";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {toast,Toaster} from "sonner";

type Booking={id:string;name:string;phone:string;service:string;date:string;time:string;status:string};
type Service={name:string;price:number;duration:number;number:string};
type Block={id:string;date:string;time:string;note:string};
const defaultServices:Service[]=[
 {name:"Acabamento / alinhamento do pezinho",price:25,duration:30,number:"01"},{name:"Barba",price:40,duration:30,number:"02"},{name:"Corte + barba",price:85,duration:60,number:"03"},{name:"Corte + barba + sobrancelha",price:100,duration:60,number:"04"},{name:"Corte degradê",price:45,duration:30,number:"05"},{name:"Corte infantil",price:45,duration:30,number:"06"},{name:"Corte máquina",price:30,duration:15,number:"07"},{name:"Corte social",price:40,duration:30,number:"08"},{name:"Corte tesoura",price:45,duration:30,number:"09"},{name:"Higienização com cera — nariz",price:25,duration:15,number:"10"},{name:"Pigmentação",price:25,duration:30,number:"11"},{name:"Luzes + corte",price:169,duration:75,number:"12"},{name:"Platinado + corte",price:175,duration:75,number:"13"},{name:"Sobrancelha",price:25,duration:15,number:"14"},
];
const times=["09:00","09:40","10:20","11:00","13:00","13:40","14:20","15:00","15:40","16:20","17:00","17:40","18:20","19:00"];
const today=()=>format(new Date(),"yyyy-MM-dd");
const pretty=(d:string)=>format(new Date(`${d}T12:00:00`),"dd 'de' MMMM",{locale:ptBR});

export default function AdminPage(){
 const[bookings,setBookings]=useState<Booking[]>([]),[services,setServices]=useState<Service[]>(defaultServices),[blocks,setBlocks]=useState<Block[]>([]);
 const[selectedDate,setSelectedDate]=useState(today()),[editing,setEditing]=useState<Booking|null>(null),[blockOpen,setBlockOpen]=useState(false),[serviceOpen,setServiceOpen]=useState(false),[createOpen,setCreateOpen]=useState(false);
 const[viewMode,setViewMode]=useState<"day"|"week">("day"),[agendaStatus,setAgendaStatus]=useState("Todos"),[clientQuery,setClientQuery]=useState("");
 const[blockForm,setBlockForm]=useState({date:today(),time:"Dia inteiro",note:""}),[serviceForm,setServiceForm]=useState<Service>({name:"",price:0,duration:30,number:""}),[createForm,setCreateForm]=useState({name:"",phone:"",service:"",date:today(),time:""});
 useEffect(()=>{let active=true;async function load(){try{const response=await fetch("/api/barber",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {bookings:Booking[];blocks:Block[];services:Service[]};if(!active)return;setBookings(data.bookings||[]);setBlocks(data.blocks||[]);if(data.services?.length)setServices(data.services);else{setServices(defaultServices);void Promise.all(defaultServices.map(service=>fetch("/api/barber",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsertService",service})})))}}catch{toast.error("Não foi possível atualizar os dados do painel.")}}queueMicrotask(load);window.addEventListener("focus",load);const timer=window.setInterval(load,15000);return()=>{active=false;window.removeEventListener("focus",load);window.clearInterval(timer)}},[]);
 const active=bookings.filter(b=>b.status!=="Cancelado"),day=bookings.filter(b=>b.date===selectedDate&&(agendaStatus==="Todos"||b.status===agendaStatus)).sort((a,b)=>a.time.localeCompare(b.time)),upcoming=active.filter(b=>b.date>=today()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 const clients=useMemo(()=>Array.from(new Map(bookings.map(b=>[b.phone,b])).values()),[bookings]);
 const clientRows=useMemo(()=>clients.map(client=>{const history=bookings.filter(b=>b.phone===client.phone).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));return{...client,visits:history.filter(b=>b.status!=="Cancelado").length,last:history[0]}}).filter(client=>`${client.name} ${client.phone}`.toLowerCase().includes(clientQuery.toLowerCase())),[bookings,clients,clientQuery]);
 const weekDays=useMemo(()=>{const base=new Date(`${selectedDate}T12:00:00`);const weekday=base.getDay()||7;base.setDate(base.getDate()-weekday+1);return Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i);return format(d,"yyyy-MM-dd")})},[selectedDate]);
 const todayRevenue=active.filter(b=>b.date===today()).reduce((sum,b)=>sum+(services.find(s=>s.name===b.service)?.price||0),0);
 const moveDay=(n:number)=>{const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()+n);setSelectedDate(format(d,"yyyy-MM-dd"))};
 async function persistBooking(booking:Booking,success:string){try{const response=await fetch("/api/barber",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({booking})});const data=await response.json() as {booking:Booking;error?:string};if(!response.ok)throw new Error(data.error);setBookings(current=>current.map(item=>item.id===booking.id?data.booking:item));toast.success(success);return true}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível atualizar o agendamento.");return false}}
 async function cancel(id:string){const booking=bookings.find(b=>b.id===id);if(booking)await persistBooking({...booking,status:"Cancelado"},"Agendamento cancelado.")}
 async function setStatus(id:string,status:string){const booking=bookings.find(b=>b.id===id);if(booking)await persistBooking({...booking,status},status==="Concluído"?"Atendimento concluído.":status==="Confirmado"?"Agendamento confirmado.":"Status atualizado.")}
 async function update(e:React.FormEvent){e.preventDefault();if(!editing)return;if(await persistBooking(editing,"Agendamento atualizado."))setEditing(null)}
 async function createBooking(e:React.FormEvent){e.preventDefault();if(!createForm.name||!createForm.phone||!createForm.service||!createForm.date||!createForm.time){toast.error("Preencha todos os dados do agendamento.");return}try{const response=await fetch("/api/barber",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createAdminBooking",booking:{...createForm,status:"Confirmado"}})});const data=await response.json() as {booking:Booking;error?:string};if(!response.ok)throw new Error(data.error);setBookings(current=>[...current,data.booking]);setSelectedDate(data.booking.date);setCreateOpen(false);setCreateForm({name:"",phone:"",service:"",date:today(),time:""});toast.success("Agendamento incluído na agenda.")}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível criar o agendamento.")}}
 async function addBlock(e:React.FormEvent){e.preventDefault();try{const response=await fetch("/api/barber",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createBlock",block:blockForm})});const data=await response.json() as {block:Block;error?:string};if(!response.ok)throw new Error(data.error);setBlocks(current=>[...current,data.block]);setBlockOpen(false);setBlockForm({date:today(),time:"Dia inteiro",note:""});toast.success("Período bloqueado.")}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível bloquear o período.")}}
 function openService(s?:Service){setServiceForm(s||{name:"",price:0,duration:30,number:String(services.length+1).padStart(2,"0")});setServiceOpen(true)}
 async function upsertService(e:React.FormEvent){e.preventDefault();if(!serviceForm.name)return;try{const response=await fetch("/api/barber",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsertService",service:serviceForm})});const data=await response.json() as {service:Service;error?:string};if(!response.ok)throw new Error(data.error);setServices(current=>current.some(s=>s.number===serviceForm.number)?current.map(s=>s.number===serviceForm.number?data.service:s):[...current,data.service]);setServiceOpen(false);toast.success("Serviço salvo.")}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar o serviço.")}}
 async function deleteBlock(id:string){try{const response=await fetch("/api/barber",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"block",id})});if(!response.ok)throw new Error();setBlocks(current=>current.filter(item=>item.id!==id));toast.success("Bloqueio removido.")}catch{toast.error("Não foi possível remover o bloqueio.")}}
 async function deleteService(number:string){try{const response=await fetch("/api/barber",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"service",id:number})});if(!response.ok)throw new Error();setServices(current=>current.filter(item=>item.number!==number));toast.success("Serviço removido.")}catch{toast.error("Não foi possível remover o serviço.")}}
 return <main className="admin-shell"><Toaster theme="dark" richColors position="top-center"/>
  <header className="admin-header"><div><Link href="/" className="brand"><Image src="/logo-bs.png" alt="BS Barber Classic" width={120} height={120}/></Link><span className="admin-divider"/><p>Painel de gestão</p></div><Link href="/" className="admin-public-link"><ArrowLeft/> Voltar ao site</Link></header>
  <div className="admin-main"><div className="admin-title"><div><p className="admin-kicker">BS BARBER CLASSIC</p><h1>Controle da barbearia</h1><p>Agenda, clientes e serviços em um único lugar.</p></div><div className="admin-title-actions"><Button variant="outline" onClick={()=>setBlockOpen(true)}><Ban/> Bloquear horário</Button><Button onClick={()=>setCreateOpen(true)}><CalendarPlus/> Novo agendamento</Button></div></div>
   <section className="stats"><article className="stat"><CalendarDays/><span>Agenda de hoje</span><strong>{active.filter(b=>b.date===today()).length}</strong><small>atendimentos</small></article><article className="stat"><CheckCircle2/><span>Confirmados</span><strong>{upcoming.filter(b=>b.status==="Confirmado").length}</strong><small>próximas reservas</small></article><article className="stat"><UsersRound/><span>Clientes</span><strong>{clients.length}</strong><small>cadastrados</small></article><article className="stat"><CircleDollarSign/><span>Previsão de hoje</span><strong>R$ {todayRevenue}</strong><small>em serviços agendados</small></article></section>
   <Tabs defaultValue="agenda" className="admin-tabs"><TabsList variant="line" className="admin-tabs-list"><TabsTrigger value="agenda"><LayoutDashboard/> Agenda</TabsTrigger><TabsTrigger value="clientes"><UsersRound/> Clientes</TabsTrigger><TabsTrigger value="servicos"><Scissors/> Serviços</TabsTrigger><TabsTrigger value="bloqueios"><Ban/> Bloqueios</TabsTrigger></TabsList>
    <TabsContent value="agenda" className="admin-grid">
     <section className="panel agenda-panel">
      <div className="panel-head agenda-head"><div><p>{viewMode==="day"?"AGENDA DO DIA":"AGENDA DA SEMANA"}</p><h2>{viewMode==="day"?pretty(selectedDate):`${pretty(weekDays[0])} — ${pretty(weekDays[6])}`}</h2></div><div className="agenda-controls"><div className="view-switch"><button className={viewMode==="day"?"active":""} onClick={()=>setViewMode("day")}><CalendarDays/> Dia</button><button className={viewMode==="week"?"active":""} onClick={()=>setViewMode("week")}><CalendarRange/> Semana</button></div><div className="date-nav"><button onClick={()=>moveDay(viewMode==="day"?-1:-7)}><ChevronLeft/></button><button onClick={()=>setSelectedDate(today())}>Hoje</button><button onClick={()=>moveDay(viewMode==="day"?1:7)}><ChevronRight/></button><label><CalendarDays/><input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></label></div></div></div>
      <div className="agenda-filter"><span>Filtrar por status</span>{["Todos","Pendente","Confirmado","Concluído","Cancelado"].map(status=><button key={status} className={agendaStatus===status?"active":""} onClick={()=>setAgendaStatus(status)}>{status}</button>)}</div>
      {viewMode==="day"?(day.length===0?<Empty icon={<CalendarDays/>} title="Nenhum agendamento neste dia" text="Use os filtros ou selecione outra data para consultar a agenda."/>:<div className="schedule-list">{day.map(b=><article className="schedule-item" key={b.id}><div className="schedule-time"><strong>{b.time}</strong><span>{services.find(s=>s.name===b.service)?.duration||40} min</span></div><div className="schedule-client"><span className="client-avatar">{b.name[0]}</span><div><strong>{b.name}</strong><small>{b.phone}</small></div></div><div className="schedule-service"><small>Serviço</small><strong>{b.service}</strong></div><span className={`status status-${b.status.toLowerCase().replace("í","i")}`}>{b.status}</span><DropdownMenu><DropdownMenuTrigger asChild><button className="row-action" aria-label={`Ações do agendamento de ${b.name}`}><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>setStatus(b.id,"Confirmado")}><CheckCircle2/> Confirmar</DropdownMenuItem><DropdownMenuItem onClick={()=>setStatus(b.id,"Concluído")}><Check/> Concluir atendimento</DropdownMenuItem><DropdownMenuItem onClick={()=>setEditing(b)}><Pencil/> Alterar dados</DropdownMenuItem><DropdownMenuItem onClick={()=>cancel(b.id)}><XCircle/> Cancelar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></article>)}</div>):<div className="week-board">{weekDays.map(date=>{const entries=bookings.filter(b=>b.date===date&&(agendaStatus==="Todos"||b.status===agendaStatus)).sort((a,b)=>a.time.localeCompare(b.time));return <article className={date===today()?"week-day today":"week-day"} key={date}><header><span>{format(new Date(`${date}T12:00:00`),"EEE",{locale:ptBR})}</span><strong>{format(new Date(`${date}T12:00:00`),"dd")}</strong><small>{entries.length} agenda{entries.length===1?"":"s"}</small></header><div>{entries.map(b=><button key={b.id} onClick={()=>setEditing(b)}><time>{b.time}</time><span><strong>{b.name}</strong><small>{b.service}</small></span></button>)}{!entries.length&&<p>Livre</p>}</div></article>})}</div>}
     </section>
     <aside className="panel next-panel"><div className="panel-head"><div><p>PRÓXIMOS</p><h2>Visão rápida</h2></div><span>{upcoming.length} reservas</span></div><div className="next-list">{upcoming.slice(0,6).map(b=><button key={b.id} onClick={()=>{setSelectedDate(b.date);setViewMode("day");setEditing(b)}}><time>{format(new Date(`${b.date}T12:00:00`),"dd MMM",{locale:ptBR})}<b>{b.time}</b></time><span><strong>{b.name}</strong><small>{b.service}</small></span><ChevronRight/></button>)}{!upcoming.length&&<p>Nenhuma reserva futura.</p>}</div></aside>
    </TabsContent>
    <TabsContent value="clientes"><section className="panel data-panel"><div className="panel-head"><div><p>RELACIONAMENTO</p><h2>Clientes</h2></div><div className="client-tools"><label><Search/><input value={clientQuery} onChange={e=>setClientQuery(e.target.value)} placeholder="Buscar cliente"/></label><span>{clients.length} cadastros</span></div></div>{!clientRows.length?<Empty icon={<UserRound/>} title={clientQuery?"Nenhum cliente encontrado":"Nenhum cliente cadastrado"} text={clientQuery?"Tente buscar por outro nome ou telefone.":"O cadastro acontece após o primeiro agendamento."}/>:<div className="client-table"><div className="table-labels"><span>Cliente</span><span>Contato</span><span>Último serviço</span><span>Atendimentos</span><span>Ação</span></div>{clientRows.map(c=><article key={c.phone}><div><span className="client-avatar">{c.name[0]}</span><strong>{c.name}</strong></div><span>{c.phone}</span><span>{c.last?.service}</span><em>{c.visits}</em><a href={`https://wa.me/55${c.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" aria-label={`Conversar com ${c.name} pelo WhatsApp`}><MessageCircle/></a></article>)}</div>}</section></TabsContent>
    <TabsContent value="servicos"><section className="panel data-panel"><div className="panel-head"><div><p>CATÁLOGO</p><h2>Serviços e preços</h2></div><Button variant="outline" onClick={()=>openService()}><Plus/> Novo serviço</Button></div><div className="service-admin-list">{services.map(s=><article key={s.number}><span>{s.number}</span><div><strong>{s.name}</strong><small>{s.duration} minutos</small></div><b>R$ {s.price.toFixed(2).replace(".",",")}</b><div className="service-actions"><button onClick={()=>openService(s)} aria-label={`Editar ${s.name}`}><Pencil/></button><button onClick={()=>deleteService(s.number)} aria-label={`Remover ${s.name}`}><Trash2/></button></div></article>)}</div></section></TabsContent>
    <TabsContent value="bloqueios"><section className="panel data-panel"><div className="panel-head"><div><p>INDISPONIBILIDADE</p><h2>Dias e horários bloqueados</h2></div><Button variant="outline" onClick={()=>setBlockOpen(true)}><Plus/> Novo bloqueio</Button></div>{!blocks.length?<Empty icon={<Clock3/>} title="Nenhum período bloqueado" text="Bloqueie folgas, compromissos ou horários indisponíveis."/>:<div className="block-list">{blocks.map(b=><article key={b.id}><CalendarDays/><div><strong>{pretty(b.date)}</strong><small>{b.time}{b.note?` · ${b.note}`:""}</small></div><button onClick={()=>deleteBlock(b.id)}><Trash2/></button></article>)}</div>}</section></TabsContent>
   </Tabs>
  </div>
  <Dialog open={!!editing} onOpenChange={x=>!x&&setEditing(null)}><DialogContent className="admin-modal"><DialogHeader><DialogTitle>Alterar agendamento</DialogTitle><DialogDescription>Atualize os dados e salve.</DialogDescription></DialogHeader>{editing&&<form onSubmit={update}><Label>Cliente</Label><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><div className="modal-grid"><div><Label>Data</Label><Input type="date" value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></div><div><Label>Horário</Label><Input type="time" value={editing.time} onChange={e=>setEditing({...editing,time:e.target.value})}/></div></div><Label>Serviço</Label><Select value={editing.service} onValueChange={service=>setEditing({...editing,service})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{services.map(s=><SelectItem key={s.name} value={s.name}>{s.name}</SelectItem>)}</SelectContent></Select><Label>Status</Label><Select value={editing.status} onValueChange={status=>setEditing({...editing,status})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Confirmado">Confirmado</SelectItem><SelectItem value="Concluído">Concluído</SelectItem><SelectItem value="Cancelado">Cancelado</SelectItem></SelectContent></Select><Button><Check/> Salvar alterações</Button></form>}</DialogContent></Dialog>
  <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="admin-modal admin-create-modal"><DialogHeader><DialogTitle>Novo agendamento</DialogTitle><DialogDescription>Inclua na agenda um cliente atendido por telefone ou WhatsApp.</DialogDescription></DialogHeader><form onSubmit={createBooking}><div className="modal-grid"><div><Label>Cliente</Label><Input value={createForm.name} onChange={e=>setCreateForm({...createForm,name:e.target.value})} placeholder="Nome do cliente"/></div><div><Label>WhatsApp</Label><Input value={createForm.phone} onChange={e=>setCreateForm({...createForm,phone:e.target.value})} placeholder="(48) 99999-9999"/></div></div><Label>Serviço</Label><Select value={createForm.service} onValueChange={service=>setCreateForm({...createForm,service})}><SelectTrigger><SelectValue placeholder="Selecione o serviço"/></SelectTrigger><SelectContent>{services.map(s=><SelectItem key={s.name} value={s.name}>{s.name} · R$ {s.price.toFixed(2).replace(".",",")}</SelectItem>)}</SelectContent></Select><div className="modal-grid"><div><Label>Data</Label><Input type="date" min={today()} value={createForm.date} onChange={e=>setCreateForm({...createForm,date:e.target.value,time:""})}/></div><div><Label>Horário</Label><Select value={createForm.time} onValueChange={time=>setCreateForm({...createForm,time})}><SelectTrigger><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{times.map(time=><SelectItem key={time} value={time} disabled={bookings.some(b=>b.date===createForm.date&&b.time===time&&b.status!=="Cancelado")||blocks.some(b=>b.date===createForm.date&&(b.time==="Dia inteiro"||b.time===time))}>{time}</SelectItem>)}</SelectContent></Select></div></div><Button><CalendarPlus/> Salvar na agenda</Button></form></DialogContent></Dialog>
  <Dialog open={blockOpen} onOpenChange={setBlockOpen}><DialogContent className="admin-modal"><DialogHeader><DialogTitle>Bloquear agenda</DialogTitle><DialogDescription>O período ficará indisponível para novos agendamentos.</DialogDescription></DialogHeader><form onSubmit={addBlock}><Label>Data</Label><Input type="date" min={today()} value={blockForm.date} onChange={e=>setBlockForm({...blockForm,date:e.target.value})}/><Label>Período</Label><Select value={blockForm.time} onValueChange={time=>setBlockForm({...blockForm,time})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Dia inteiro">Dia inteiro</SelectItem>{times.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><Label>Motivo (opcional)</Label><Input value={blockForm.note} onChange={e=>setBlockForm({...blockForm,note:e.target.value})}/><Button><Ban/> Confirmar bloqueio</Button></form></DialogContent></Dialog>
  <Dialog open={serviceOpen} onOpenChange={setServiceOpen}><DialogContent className="admin-modal"><DialogHeader><DialogTitle>{services.some(s=>s.number===serviceForm.number)?"Editar serviço":"Novo serviço"}</DialogTitle><DialogDescription>Defina o serviço disponível no agendamento.</DialogDescription></DialogHeader><form onSubmit={upsertService}><Label>Nome</Label><Input value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})}/><div className="modal-grid"><div><Label>Preço</Label><Input type="number" min="0" value={serviceForm.price} onChange={e=>setServiceForm({...serviceForm,price:+e.target.value})}/></div><div><Label>Duração</Label><Input type="number" min="5" value={serviceForm.duration} onChange={e=>setServiceForm({...serviceForm,duration:+e.target.value})}/></div></div><Button><Check/> Salvar serviço</Button></form></DialogContent></Dialog>
 </main>
}

function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-state"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
